### ISSUE TITLE
Error "Option `subject` specified more than once" when setting any subject

### ISSUE THREAD

**Issue by dystopia2017** [animetosho/Nyuu#101]
Hello, this is my basic command

`%apps%\nyuu.exe -h %serv% -ssl -u %user% -p %pass% -f %from% -g %grps% %suba% "%dirn% %subb%" -o "%nzbd%\%dirn%.nzb" "%outd%\%dirn%\"`

Which expands to something like this for example.

`C:\bin\nyuu.exe -h news.server.com -ssl -u "user" -p "pass" -f "user user@host.com" -g alt.binaries.test -F --subject "Test Post 0001 - {filename} yEnc ({part}/{parts})" -o "S:\_Posting_\_Toolset_\_Nzbs_\Test Post 0001.nzb" "S:\_Posting_\_Toolset_\_Posting_\Test Post 0001\"
`
which errors out with 
```
Option `subject` specified more than once
Enter `nyuu --help` or `nyuu --help-full` for usage information
```
If I change --subject to anything for example "--subject test" it still returns the same error.
if I remove --subject, then it posts fine without issue. Whats going wrong? is something else in my command messing things up?

Edit: My variables if it helps

```
ser apps=C:\bin
set dirn=Test Post 0001
set nzbd=S:\_Posting_\_Toolset_\_Nzbs_
set odir=S:\_Posting_\_Toolset_\_Posting_
set serv=news.server.com
set user="user"
set pass="pass"
set from="user user@host.com"
set grps=alt.binaries.test
set suba=-F --subject
set subb=- {filename} yEnc ({part}/{parts})
```

**Comment by animetosho** [comment]
I'm guessing it's because your `-ssl` option is typo'd. You probably meant `--ssl` there.

`-s` is the shorthand syntax for `--subject`, so `-ssl` is interpreted as *set the subject to 'sl'* - i.e. two subjects have been specified.

**Comment by dystopia2017** [comment]
> I'm guessing it's because your `-ssl` option is typo'd. You probably meant `--ssl` there.
> 
> `-s` is the shorthand syntax for `--subject`, so `-ssl` is interpreted as _set the subject to 'sl'_ - i.e. two subjects have been specified.

Thank you very much "-ssl" instead of "--ssl" was indeed the issue.
Thanks again and thanks for your excellent software :)
