### ISSUE TITLE
Crashes while posting

### ISSUE THREAD

**Issue by dystopia2017** [animetosho/Nyuu#102]
Hello, So I tried to make some posts tonight and had two crashes which I have posted below. In each case posting was aborted. Is there anyway to cleanly resume the posts or I have to start over? is there anything I am doing that is wrong that could have caused the issues also?

This is my basic workflow.

> @echo off
> :SetupVariables
> set idir=S:\_UP_
> set outd=S:\_UP_\_Toolset_\_Posting_
> set pstd=S:\_UP_\_Toolset_\_Posted_
> set nzbd=S:\_UP_\_Toolset_\_Nzbs_
> set apps=S:\_UP_\_Toolset_\_Apps_
> set serv=news.server.com
> set user="user"
> set pass="pass"
> set from="user user@host.com"
> set grps=alt.binaries.test
> set suba=-F --subject
> set subb=- {filename} yEnc ({part}/{parts})
> set dirn=Directory Name
> :Post
> %apps%\nyuu.exe -h %serv% --ssl -u %user% -p %pass% -f %from% -g %grps% %suba% "%dirn% %subb%" -o "%nzbd%\%dirn%.nzb" "%outd%\%dirn%"
> move "%outd%\%dirn%" %pstd%\

Here is the first one, it was posting fine then all of a suddon it had a connection error, it reconnected and continued posting
fine, then it stopped a couple of files later and moved to the next command in my script which is to move the directory being posted to a completed directory. There is no indication as to why it stopped posting.

> [INFO] Reading file file.r31...
> [WARN] NNTP connection error occurred: Response timed out (post-data); will retry post-upload request (attempt 1/5)
> [WARN] NNTP connection error occurred during close: read ECONNRESET
> [INFO] Reading file file.r32...
> [INFO] Reading file file.r33...
>  32.25%  [===========                        ] 1575 KiB/s, ETA 03:05:38        1 dir(s) moved.
> Press any key to continue . . .

This is the second crash with a crash dump. It's just stopped mid post, everything was fine up until .r20 began posting

> [INFO] Reading file file.r20...
>  26.41%  [=========                          ] 2975 KiB/s, ETA 49:45Stacktrace:
>    ptr1=2A7813ED
>     ptr2=00000000
>     ptr3=00000000
>     ptr4=00000000
>     failure_message_object=022F30C0
> 
> ==== JS stack trace =========================================
> 
>     0: ExitFrame [pc: 015813A7]
>     1: StubFrame [pc: 015D0207]
> Security context: 0x3f700469 <JSObject>
>     2: _onData [30D699D9] [_third_party_main.js:3868] [bytecode=055ADB35 offset=169](this=0x3f73fb91 <NNTP map = 3933875D>,0x2a796a8d <Uint8Array map= 393127DD>)
>     3: readableAddChunk(aka readableAddChunk) [2983FA3D] [_stream_readable.js:~221] [pc=0783834C](this=0x04a40279 <undefined>,0x3f73f43d <TLSSocket map = 3933401D>,0x2a796a8d <Uint8Array map = 393127DD>,0x04a40279 <undefined>,0x04a403c1 <false>)
>     4: onStreamRead [2983FA5D] [internal/stream_base_commons.js:~165] [pc=07802FA3](this=0x3f73b04d <TLSWrap map = 39333FF5>,0x2a796a6d <ArrayBuffer map = 393003FD>)
>     5: InternalFrame [pc: 0151194D]
>     6: EntryFrame [pc: 0151176B]
> 
> ==== Details ================================================
> 
> [0]: ExitFrame [pc: 015813A7]
> [1]: StubFrame [pc: 015D0207]
> [2]: _onData [30D699D9] [_third_party_main.js:3868] [bytecode=055ADB35 offset=169](this=0x3f73fb91 <NNTP map = 3933875D>,0x2a796a8d <Uint8Array map =393127DD>) {
>   // expression stack (top to bottom)
>   [14] : 0x04a40279 <undefined>
>   [13] : 0x04a40279 <undefined>
>   [12] : 0x04a40279 <undefined>
>   [11] : 0x00909f95 <String[#2]\: \r\n>
>   [10] : 0x2a7813ed <Very long string[#77858397]>
>   [09] : 0x3f705975 <JSFunction indexOf (sfi = 149CB3D1)>
>   [08] : 0x04a40279 <undefined>
>   [07] : 0x04a40279 <undefined>
>   [06] : 0x04a40279 <undefined>
>   [05] : 0x04a40279 <undefined>
>   [04] : 0x04a40279 <undefined>
>   [03] : 0x04a40279 <undefined>
>   [02] : 0x04a40279 <undefined>
>   [01] : 18
>   [00] : 0x2a796ab9 <String[20]\: 240 Article Posted\r\n>
> --------- s o u r c e   c o d e ---------
> function _onData(chunk) {\x0a\x09\x09this.bytesRecv += chunk.length;\x0a\x09\x09// grab incomming lines\x0a\x09\x09var data;\x0a\x09\x09if(ENCODING)\x
> 0a\x09\x09\x09data = chunk.toString(ENCODING);\x0a\x09\x09else\x0a\x09\x09\x09data = chunk.toString();\x0a\x09\x09\x0a\x09\x09var p = data.indexOf('\r
> \n');\x0a\x09\x09if(p < 0) {\x0a\x09\x09\x09p = false;\x0a\x09\x09\x09// check annoying case of a \r and \n in separate chunks\x0a\x09\x09\x09if(thi..
> .
> 
> -----------------------------------------
> }
> [3]: readableAddChunk(aka readableAddChunk) [2983FA3D] [_stream_readable.js:~221] [pc=0783834C](this=0x04a40279 <undefined>,0x3f73f43d <TLSSocket map
> = 3933401D>,0x2a796a8d <Uint8Array map = 393127DD>,0x04a40279 <undefined>,0x04a403c1 <false>) {
> // optimized frame
> --------- s o u r c e   c o d e ---------
> function readableAddChunk(stream, chunk, encoding, addToFront) {\x0a  debug('readableAddChunk', chunk);\x0a  const state = stream._readableState;\x0a\
> x0a  let err;\x0a  if (!state.objectMode) {\x0a    if (typeof chunk === 'string') {\x0a      encoding = encoding || state.defaultEncoding;\x0a      if
>  (addToFront && state.encoding && state.encoding ...
> 
> -----------------------------------------
> }
> [4]: onStreamRead [2983FA5D] [internal/stream_base_commons.js:~165] [pc=07802FA3](this=0x3f73b04d <TLSWrap map = 39333FF5>,0x2a796a6d <ArrayBuffer map
>  = 393003FD>) {
> // optimized frame
> --------- s o u r c e   c o d e ---------
> function onStreamRead(arrayBuffer) {\x0a  const nread = streamBaseState[kReadBytesOrError];\x0a\x0a  const handle = this;\x0a  const stream = this[own
> er_symbol];\x0a\x0a  stream[kUpdateTimer]();\x0a\x0a  if (nread > 0 && !stream.destroyed) {\x0a    let ret;\x0a    let result;\x0a    const userBuf =
> stream[kBuffer];\x0a    if (userBuf) {\x0a      result = (st...
> 
> -----------------------------------------
> }
> [5]: InternalFrame [pc: 0151194D]
> [6]: EntryFrame [pc: 0151176B]
> =====================

**Comment by dystopia2017** [comment]
I just tried posting again to see if it would resume but it did not, it started over, and again it crashed.
[https://i.imgur.com/h3imqZe.png](url)
This seems to be the issue this time "FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory"
but the system has idle except for posting and has lots of memory available.

> [INFO] Reading file file.r21...
> [WARN] NNTP connection error occurred: Response timed out (post-data); will retry post-upload request (attempt 1/5)
> [WARN] NNTP connection error occurred during close: read ECONNRESET
>  27.42%  [=========                          ] 1925 KiB/s, ETA 01:14:31
> <--- Last few GCs --->
> 
> [47340:020214C0]  1080503 ms: Scavenge 6.4 (7.4) -> 5.5 (7.4) MB, 0.3 / 0.0 ms  (average mu = 0.997, current mu = 0.997) allocation failure
> [47340:020214C0]  1099754 ms: Scavenge 6.5 (7.4) -> 5.7 (7.7) MB, 0.3 / 0.0 ms  (average mu = 0.997, current mu = 0.997) allocation failure
> [47340:020214C0]  1128286 ms: Scavenge 6.6 (7.7) -> 5.8 (7.7) MB, 0.5 / 0.0 ms  (average mu = 0.997, current mu = 0.997) allocation failure
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
>     0: ExitFrame [pc: 015813A7]
>     1: StubFrame [pc: 015D0332]
> Security context: 0x3969272d <JSObject>
>     2: onStreamRead [2051CC79] [internal/stream_base_commons.js:171] [bytecode=21D6CC31 offset=32](this=0x3969303d <TLSWrap map = 356B3FF5>,0x05ea6275
>  <ArrayBuffer map = 356803FD>)
>     3: InternalFrame [pc: 0151194D]
>     4: EntryFrame [pc: 0151176B]
> 
> ==== Details ================================================
> 
> [0]: ExitFrame [pc: 0158...
> 
> FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory

**Comment by animetosho** [comment]
I assume you're using the Windows binaries from [here](https://github.com/animetosho/Nyuu/releases/tag/v0.4.1)?  
If so, it looks like the build really messed up - don't know why.

I've replaced it with the source version, which seems to work much better, but there's no nyuu.exe in this version.  
Could you try downloading the new version and try again?

Unfortunately Nyuu currently does not have any resume capabilities, so all uploads will start from the beginning.

Thanks for the report!

**Comment by dystopia2017** [comment]
> I assume you're using the Windows binaries from [here](https://github.com/animetosho/Nyuu/releases/tag/v0.4.1)? If so, it looks like the build really messed up - don't know why.
> 
> I've replaced it with the source version, which seems to work much better, but there's no nyuu.exe in this version. Could you try downloading the new version and try again?
> 
> Unfortunately Nyuu currently does not have any resume capabilities, so all uploads will start from the beginning.
> 
> Thanks for the report!

Thanks for the updated, I have been posting all day with the source version and it seems very stable now, not had any issues at all :)

**Comment by animetosho** [comment]
Thanks for confirming.

I think I've found the cause, and have replaced the build with the single-EXE version. Let me know if it works for you if you decide to test it.
