### ISSUE TITLE
Feature Request: Accept range in `${rand(N)}`

### ISSUE THREAD

**Issue by Ravencentric** [animetosho/Nyuu#109]
Something like `${rand(10,20)}`

**Comment by animetosho** [comment]
What would that do, and why/what is its purpose?

**Comment by Ravencentric** [comment]
Further obfuscation. Using a fixed digit for all my uploads still means I'm leaving a pattern behind

**Comment by animetosho** [comment]
Thanks for the explanation. I'm not convinced it makes any difference, and sounds very niche, but if you believe this is valuable, you can assign [custom functions in config.js](https://github.com/animetosho/Nyuu/blob/ec27439cd30f970d1ef1ace5ba317125291815d1/config.js#L96-L99) to get the exact behavior you're looking for.

**Comment by Ravencentric** [comment]
It might be niche but it's another layer of obfuscation and security

**Comment by animetosho** [comment]
The design of config.js was done for such niche cases - a Javascript function can be written to cater for any scenario you feel is necessary.

Though I had another idea for your specific scenario. You can use the new `--token-eval`/`-E` parameter to evaluate Javascript in a parameter instead, e.g. `-E --subject '${rand((10+Math.random()*11)|0)}'`

**Comment by Ravencentric** [comment]
So I've been playing with this today and it's almost perfect, very much appreciate it and thank you for considering it :D

So these are my results (I didn't use `'${rand((10+Math.random()*11)|0)}'` because windows doesn't like `|`)
```shell
nyuu -C nyuu.json -E --from ${rand(Math.floor(Math.random()*(20-10)+10))}@test.abc --log-time --skip-errors all --subdirs keep --subject ${rand(Math.floor(Math.random()*(20-10)+10))} --yenc-name ${rand(Math.floor(Math.random()*(20-10)+10))} --nzb-subject "[{0filenum}/{files}] - "{filename}" yEnc ({part}/{parts}) {filesize}" -g alt.binaries.boneless -o "helck2.nzb" "helck"
````

The randomizer [works perfectly](http://al.howardknight.net/?STYPE=msgid&MSGI=%3CVfAjOkPwGxSjCuKnAoHcDqRr-1691353788435@nyuu%3E) but the `-E` also means the nzb-subject now doesn't get evaluated and just writes it as is in the nzb file. Reading the help this does seem expected behavior but not ideal. Apologies since I cant provide much in terms of solution due to my lack of proficiency here.
![image](https://github.com/animetosho/Nyuu/assets/78981416/0f904d08-a9ed-46e1-a945-21161063e280)

**Comment by animetosho** [comment]
`-E` [affects all token fields](https://github.com/animetosho/Nyuu/blob/8175ad16d12046eadf2406cf922752cec3226aab/help-full.txt#L411-L428), so you'll need to adapt `--nzb-subject` accordingly (needs to be formatted as [a template string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

**Comment by Ravencentric** [comment]
Thank you!
