### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by Ravencentric** [animetosho/Nyuu#114]
There's been quite alot of changes in Nyuu recently but they haven't made their way into either binaries or [npm](https://www.npmjs.com/package/nyuu)

**Comment by loungebob** [comment]
Upvote this. Also, do I use the the 32bit v0.4.1 on a Win10 64bit or the older v0.4.0 64bit Win release?

**Comment by animetosho** [comment]
64-bit Windows can run both 32-bit and 64-bit binaries. 32-bit has greater compatibility, so I often prefer to release that.

**Comment by animetosho** [comment]
v0.4.2 has now been released.
