### ISSUE TITLE
Tokens are not replaced on metadata

### ISSUE THREAD

**Issue by javi11** [animetosho/Nyuu#116]
Hi, first of all amazing work here :).

Now, I was trying to add some metadata into the nzb using the token {size} as it says on the documentation https://github.com/animetosho/Nyuu/blob/c7c4ff1d920d80a3b2ea4b25294cd97b6518e638/help-full.txt#L324. Seems that since the metadata is generated before have this information and this info is only related to one file, is not being replaced. 
In that case I think it should be great to specify on the documentation that even is the same syntax as headers it do not support tokens. Wtd?

**Comment by animetosho** [comment]
Nice catch, thanks!
