### ISSUE TITLE
On Windows: "Error: No files to process"

### ISSUE THREAD

**Issue by incorpusyehtee** [animetosho/Nyuu#12]
Node: 6.9.2
NPM: 3.10.9

```
user@machine: C:\bin\nyuu\bin
$ node nyuu C:\test
Skipping directory: C:\test
Error: No files to process
```

I tried wrapping the directory in quotes as well. Any help is appreciated.

![capture_-_2016-12-10_04-10-49](https://cloud.githubusercontent.com/assets/8435612/21071117/c972a108-be64-11e6-808a-aecc14a0bac6.png)

**Comment by animetosho** [comment]
Try appending `--subdirs=keep` to your command line.

**Comment by mrsieb** [comment]
node nyuu C:\test\*.*

**Comment by incorpusyehtee** [comment]
Thanks for the suggestions! The subdirs switch works for me.

![capture_-_2016-12-10_18-36-17](https://cloud.githubusercontent.com/assets/8435612/21075358/cbc9db0a-bedd-11e6-859e-1ffcd09c3082.png)
