### ISSUE TITLE
mistake

### ISSUE THREAD

**Issue by inqges** [animetosho/Nyuu#120]
no one told you that maybe your mother made a big mistake?

what motivates someone to write a poster for obfuscated junk?

to make it possible indexing websites to earn?

to feel pleasure you destroyed something?

**Comment by animetosho** [comment]
Unfortunately, I'm not able to tell what your issue is and what/if you're trying to suggest something.

Would you be able to clarify?

**Comment by heartdeadz** [comment]
gay
