### ISSUE TITLE
 --from '${rand(13)}@${rand(5)}.${rand(3)}' not working

### ISSUE THREAD

**Issue by JoshBeer** [animetosho/Nyuu#122]
Hi,

I'm using the current release 0.4.1 (nyuu-v0.4.1-linux-amd64) and using the option `--from '${rand(13)}@${rand(5)}.${rand(3)}'`
literally results in `From: ${rand(13)}@${rand(5)}.${rand(3)}`

`--subject '${rand(30)}'` is working as expected.

It must have worked at some point. Ravencentric had it working in his issue example: 
https://github.com/animetosho/Nyuu/issues/108
http://al.howardknight.net/?STYPE=msgid&MSGI=%3CEwKvLqQhVjQzOmCsTzYwQmAl-1690827836747@nyuu%3E

Cheers!

**Comment by animetosho** [comment]
Tokens aren't supported in that option in the current release version. It's only available in the development (Git) code.

**Comment by JoshBeer** [comment]
Thanks for the clarification! :)
