### ISSUE TITLE
Dont write NZB on errors

### ISSUE THREAD

**Issue by Fossil01** [animetosho/Nyuu#126]
Looks like a valid NZB is being written when uploading is incomplete due to "too many connections" errors. This is using --nzb-cork option.

Any way to fail it and delete the NZB when this happens?

**Comment by animetosho** [comment]
If you're running this in a script, you can check the error code and if it's not 0, delete the file.

Does that help?

**Comment by animetosho** [comment]
I think I had something half written to do this - I can look at completing it.

**Comment by animetosho** [comment]
`--nzb-del-incomplete` is probably want you want.

**Comment by animetosho** [comment]
> Thats the only param?

Yes.

It only deletes the file if Nyuu exits prematurely. If Nyuu is still running, it won't delete it.  
Note that skipping errors won't cause Nyuu to exit prematurely on those.

> But perhaps it just retried the connection and actually succeeded.

You can check the NZB to see if all the articles are present there.
