### ISSUE TITLE
Extremely slow up speed with Node v20

### ISSUE THREAD

**Issue by duhagppn** [animetosho/Nyuu#128]
Updated my seedbox earlier and it upgraded to node v20.12.1 (previous version 18) and the upload speed has taken a nosedive:

```
Posted: 0+2/23137 (0.00%) @ 31.9 KiB/s (network: 808.87 KiB/s) ETA 1d,08:08:00
```

After reverting to v18.20.1 the speed is back to normal

```
Posted: 59+692/23137 (1.75%) @ 86.3 MiB/s (network: 80.17 MiB/s) ETA 06:33
```

did the npm install/rebuild/etc stuff. is this is a bug with newer node versions?

**Comment by animetosho** [comment]
Thanks for finding!

I think the above commit resolves the issue - let me know if it doesn't.
