### ISSUE TITLE
[Windows] Subject fields (like {files}, {filenum}, etc) not populating

### ISSUE THREAD

**Issue by incorpusyehtee** [animetosho/Nyuu#13]
Using `--subject '{comment} [{files}/{filenum}] - "{filename}" yEnc ({part}/{parts}) {filesize}'` leads to collections with `{comment} [undefined/undefined] - undefined yEnc (undefined/undefined) undefined` as their subject line.

Using `--log-level 4` does not seem to indicate any errors determining the subject or anything so I am guessing this is currently unsupported.

Seemingly as a result of this the NZB files contain references to segments of the "same" file, so clients cannot parse them.

I am essentially using `node nyuu.js --comment 'comment' --subdirs=keep C:\directory\` and also tried the `--group-files` switch with that command having a subdirectory in `C:\directory` with a name.

 I also tried using a list of files as the input, like `"C:\directory\file.par2","C:\directory\file.rar","C:\directory\file.r00", . . .` (with double quotes, single quotes, and no quotes) but that was purely speculation on my part.

Thanks again!

**Comment by animetosho** [comment]
There's a bug there, so thanks for reporting that!

`{comment}` and `{comment2}` are actually unavailable as placeholders, they're only shown for demonstrative purposes, but I can see how that can be confusing, so I'll change that.

When specifying multiple files manually, you can just separate them with spaces (don't use commas).  Example: `node nyuu.js "C:\file1" "C:\file2"`
