### ISSUE TITLE
About upload

### ISSUE THREAD

**Issue by CevreMuhendisi** [animetosho/Nyuu#130]
im using nzb-safeloader with nyuu. I've started using Nyuu, but when I try to upload files from a folder, it zips them all before posting. Is there a way to upload the files individually instead?

**Comment by animetosho** [comment]
Nyuu doesn't contain any zipping code. You'll need to direct the question to nzb-safeloader.

There may also be other scripts which more closely align with what you want. For example, [juicenet-cli](https://github.com/Ravencentric/juicenet-cli) claims to not do any archiving.
