### ISSUE TITLE
Unexpected fatal exception encountered "_third_party_main.js:1265"

### ISSUE THREAD

**Issue by dystopia2017** [animetosho/Nyuu#138]
Hello, I have been posting fine for months but today I got an error. This week I did a fresh install of Windows 11 24H2 and installed the latest node.js but now when I try to do a post I get this error. Any ideas if I am doing something wrong?

```
[INFO] Uploading 392935 article(s) from 62 file(s) totalling 749.39 GiB
[INFO] Reading file REMOVED.7z.001...
[ERR ] Unexpected fatal exception encountered, stack trace below
_third_party_main.js:1265
                        throw err; // this seems to change the exit code a bit :/
                        ^

Error: ENOENT: no such file or directory, open 'Q:\_OUPS_\_Toolset_\Nzbs\REMOVED.nzb'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:361:12
    at FSReqCallback.oncomplete (fs.js:156:23) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'Q:\\_OUPS_\\_Toolset_\\Nzbs\\REMOVED.nzb'
}
```

My command is

`Q:\_OUPS_\_Toolset_\Apps\nyuu -M password="REMOVED" -h "REMOVED" --port "563" --ssl -u "REMOVED" -p "REMOVED" -f "REMOVED" -g REMOVED -F --subject "REMOVED - {REMOVED} yEnc ({part}/{parts})" -n 30 --check-connections=1 --check-tries 2 --check-delay 5 --check-post-tries 10  -a 2000K -o "Q:\_OUPS_\_Toolset_\Nzbs\REMOVED.nzb" "Q:\\REMOVED"
`

![error](https://github.com/user-attachments/assets/f910c8cb-0508-4044-a037-1b02f7fa87af)

**Comment by animetosho** [comment]
The error says it couldn't open that file - is the path valid (all directories exist) and is that file writable?

**Comment by dystopia2017** [comment]
> The error says it couldn't open that file - is the path valid (all directories exist) and is that file writable?

Thanks I now see the issue, my nzb is set to be appended with "Posted_On_TodaysDate" like this

`-o "%Nzbd%\%inpt%_(Posted_On_%pdat%).nzb"`

And for some reason the date format has changed in 24h2
I was doing this to set the date previously

```
for /F "usebackq tokens=1,2 delims==" %%i in (`wmic os get LocalDateTime /VALUE 2^>NUL`) do if '.%%i.'=='.LocalDateTime.' set date=%%j
set pdat=%date:~0,4%%date:~4,2%%date:~6,2%
```

Which would output a date like "20241203" but in 24h2 this has become broken and outputs as "03/12/20" so the /'s in the broken date made nyuu think it was directories in a path. Changing my script to set the date like this fixes the issue.

```
for /F "usebackq tokens=1,2 delims==" %%i in (`wmic os get LocalDateTime /VALUE 2^>NUL`) do if '.%%i.'=='.LocalDateTime.' set date=%%j
set date=%date:~6,4%%date:~3,2%%date:~0,2%
```

Thanks again for pointing me in the direction of the error and for the wonderful nyuu :)
