### ISSUE TITLE
Change a.b.grp per file upload?

### ISSUE THREAD

**Issue by scriptzteam** [animetosho/Nyuu#16]
Is there a ways as file is being uploaded to change a.b.group, so scenario:

I have /DIR/Sub-dir-blahblah/

Lets gonna upload Sub-dir-blahblah, there are files file1.rar and file2.rar and so on contiinues until file50.rar, nyuu then rotate different newsgroups from some list (defined in *.txt file or so) and upload every file*.rar into different newsgroup.

Thanks.

**Comment by animetosho** [comment]
You could just have a script which just calls Nyuu multiple times with a different group for each run.

Alternatively, you can make use of the `Newsgroups` value in config.js and write a custom function to rotate groups based on the filename. How you do it will obviously depend on exactly how you want your rotation to work.

**Comment by scriptzteam** [comment]
I mean it like this i have folder  /DIR/Sub-dir-blahblah/ and files  file1.rar and file2.rar

and file  file1.rar will end in a.b.something and file2.rar will end uploaded in a.b.test for example, i dont need any file matching function just some random array, in this array will be all grps like

grps = [test, test2, bla, blabla, etc]

can you point me right direction please? :)

THX!

**Comment by scriptzteam** [comment]
Okay i done that but now how i can upload all files from ONE folder into different groups, i just need randomize t from maybe a text file or array? Can you help me please ?

**Comment by animetosho** [comment]
Pretty much same answer as given above. You can invoke Nyuu on a per file basis, with a different group.  
Nyuu does not, and never ever did, operate on or deal with folders. Nyuu always operates on files, so it's up to you to supply the correct input.

**Comment by scriptzteam** [comment]
Thats all nice i know that probly bbbut i asked "If you can give me a hint which code line is suppossed to be the cause of single FILE uploading not whole folders but file uploading, then i can code it myself" thx!

**Comment by scriptzteam** [comment]
Could it be done here for example -> https://github.com/animetosho/Nyuu/blob/d2732307da3a73a75fb265a353f6c709abed8fc9/lib/fileuploader.js#L196  ???

I am using this code:

```
var selectFruit = ["prof","chello","buenohora","dgma","dc","big","montolos","storage","fuborot","fz","ufo","cbt","jerry","veraeter","rudystha","doktor","load","ratcave","cccb","wb","ftr","$
var pickAFruit = function () {
var todaysFruit = selectFruit[Math.floor(Math.random() * 47)];
return "alt.binaries." + todaysFruit;
}
```

this will print random group `pickAFruit()` all i need to do is somehow insert it so Nyuu will rotate them per every file upload gets random group from selectFruit
