### ISSUE TITLE
Weir error

### ISSUE THREAD

**Issue by scriptzteam** [animetosho/Nyuu#17]
What can cause this??

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: 140042964944704:error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:s3_pkt.c:1472:SSL alert number 20

    at Error (native)

**Comment by animetosho** [comment]
What version are you running? Latest stable (v0.3.0 from releases page) or some git revision? If the latter, you'll need to always update your git revision to the latest code, if you're not already.

If you're already running the latest git version, could you explain how you got the error?

**Comment by scriptzteam** [comment]
latest git :)

its when uploading see

```
[INFO] Uploading 4851 article(s) from 3 file(s) totalling 3314.48 MiB
[INFO] Reading file ***.mkv...
[WARN] NNTP connection unexpectedly lost, reconnecting and retrying last request... (attempt 1/5000)
 87.65%  [==============================     ] 28.03 MiB/s, ETA 00:15
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: 140059732752192:error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:s3_pkt.c:1472:SSL alert number 20

    at Error (native)

```

**Comment by animetosho** [comment]
Thanks for posting the info, but I can't really identify it unfortunately.

Could you give the following details:

* Commit hash that you're currently on
* Command used to run Nyuu, and any config changes that you've done
* How often does this occur?
* Is this always after an "NNTP connection unexpectedly lost" error?
* What version of nodejs are you using?

I thought I had fixed the issue in commit beb519f37cb8f9fb6e9948a48edff55f7e7f9eac ...

**Comment by scriptzteam** [comment]
Yep its latest git :)

I think it comes directly from invalid certificate -> news.usenet.farm port 563, when i switch to port 119 problem gone ...

```
[WARN] NNTP connection unexpectedly lost, reconnecting and retrying last request... (attempt 1/5e+25)
[WARN] NNTP connection unexpectedly lost, reconnecting and retrying last request... (attempt 1/5e+25)
[WARN] NNTP connection error occurred during close: write EPIPE
[WARN] NNTP connection error occurred: read ECONNRESET; will retry last request (attempt 1/5e+25)
[WARN] NNTP connection unexpectedly lost, reconnecting and retrying last request... (attempt 1/5e+25)
[WARN] NNTP connection error occurred during close: 140315355510592:error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:s3_pkt.c:1472:SSL alert number 20

[WARN] NNTP connection unexpectedly lost, reconnecting and retrying last request... (attempt 1/5e+25)
[WARN] NNTP connection error occurred during close: 140315355510592:error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:s3_pkt.c:1472:SSL alert number 20
```

**Comment by animetosho** [comment]
Thanks again for the info. Did you just update Nyuu? From your output, it looks like the error is being handled now.

It can't be an invalid certificate, because it wouldn't upload at all if that was the case. It looks like you're just getting odd disconnects.

Also, what version of node are you running? You can check with `nodejs -v`. If it's <4, maybe updating to a newer version helps (newer versions of node have better SSL handling).

**Comment by scriptzteam** [comment]
thecubenet when upload sooo ?

 reconnecting after 5 second(s)... (attempt 2/1000)
[WARN] NNTP connection failed: Hostname/IP doesn't match certificate's altnames: "Host: secure.europe.thecubenet.com. is not in the cert's altnames: DNS:*.sslusenet.com, DNS:sslusenet.com", reconnecting after 5 second(s)... (attempt 2/1000)
[WARN] NNTP connection failed: Hostname/IP doesn't match certificate's altnames: "Host: secure.europe.thecubenet.com. is not in the cert's altnames: DNS:*.sslusenet.com, DNS:sslusenet.com", reconnecting after 5 second(s)... (attempt 2/1000)
[WARN] NNTP connection failed: Hostname/IP doesn't match certificate's altnames: "Host: secure.europe.thecubenet.com. is not in the cert's altnames: DNS:*.sslusenet.com, DNS:sslusenet.com", reconnecting after 5 second(s)... (attempt 2/1000)
[WARN] NNTP connection failed: Hostname/IP doesn't match certificate's altnames: "Host: secure.europe.thecubenet.com. is not in the cert's altnames: DNS:*.sslusenet.com, DNS:sslusenet.com", reconnecting after 5 second(s)... (attempt 2/1000)
[WARN] NNTP connection failed: Hostname/IP doesn't match certificate's altnames: "Host: secure.europe.thecubenet.com. is not in the cert's altnames: DNS:*.sslusenet.com, DNS:sslusenet.com", reconnecting after 5 second(s)... (attempt 2/1000)
[WARN] NNTP connection failed: Hostname/IP doesn't match certificate's altnames: "Host: secure.europe.thecubenet.com. is not in the cert's altnames: DNS:*.sslusenet.com, DNS:sslusenet.com", reconnecting after 5 second(s)... (attempt 2/1000)
[WARN] NNTP connection failed: Hostname/IP doesn't match certificate's altnames: "Host: secure.europe.thecubenet.com. is not in the cert's altnames: DNS:*.sslusenet.com, DNS:sslusenet.com", reconnecting after 5 second(s)... (attempt 2/1000)
[WARN] NNTP connection failed: Hostname/IP doesn't match certificate's altnames: "Host: secure.europe.thecubenet.com. is not in the cert's altnames: DNS:*.sslusenet.com, DNS:sslusenet.com", reconnecting after 5 second(s)... (attempt 2/1000)
[WARN] NNTP connection failed: Hostname/IP doesn't match certificate's altnames: "Host: secure.europe.thecubenet.com. is not in the cert's altnames: DNS:*.sslusenet.com, DNS:sslusenet.com", reconnecting after 5 second(s)... (attempt 3/1000)

**Comment by animetosho** [comment]
Now *that* is an example of an invalid SSL certificate.

**Comment by scriptzteam** [comment]
so any way to solve these :D

**Comment by animetosho** [comment]
Well, some options:

* get the provider to fix their SSL certificate
* don't use SSL
* ignore invalid SSL certificates with `--ignore-cert`

**Comment by scriptzteam** [comment]
Well another one, latest git, probably when on error it does not close connection and it still stay at connected even error happens ?

```
[INFO] Reading file pl-flehun14.r25...
[INFO] Reading file pl-flehun14.r26...
[INFO] Reading file pl-flehun14.r27...
[WARN] NNTP connection failed: Unexpected response to auth pass (code: 482): Too many connections for your user., reconnecting after 5 second(s)... (attempt 4/1000)
[WARN] NNTP connection failed: Unexpected response to auth pass (code: 482): Too many connections for your user., reconnecting after 5 second(s)... (attempt 4/1000)
[WARN] NNTP connection failed: Unexpected response to auth pass (code: 482): Too many connections for your user., reconnecting after 5 second(s)... (attempt 4/1000)
[WARN] NNTP connection failed: Unexpected response to auth pass (code: 482): Too many connections for your user., reconnecting after 5 second(s)... (attempt 4/1000)
[WARN] NNTP connection failed: Unexpected response to auth pass (code: 482): Too many connections for your user., reconnecting after 5 second(s)... (attempt 4/1000)
[WARN] NNTP connection failed: Unexpected response to auth pass (code: 482): Too many connections for your user., reconnecting after 5 second(s)... (attempt 4/1000)
[WARN] NNTP connection failed: Unexpected response to auth pass (code: 482): Too many connections for your user., reconnecting after 5 second(s)... (attempt 4/1000)
[WARN] NNTP connection failed: Unexpected response to auth pass (code: 482): Too many connections for your user., reconnecting after 5 second(s)... (attempt 4/1000)
[WARN] NNTP connection failed: Unexpected response to auth pass (code: 482): Too many connections for your user., reconnecting after 5 second(s)... (attempt 4/1000)
[WARN] NNTP connection failed: Unexpected response to auth pass (code: 482): Too many connections for your user., reconnecting after 5 second(s)... (attempt 4/1000)
[INFO] Reading file pl-flehun14.r28...
[INFO] Reading file pl-flehun14.r29...
[INFO] Reading file pl-flehun14.r30...
[INFO] Reading file pl-flehun14.r31...
[INFO] Reading file pl-flehun14.r32...
 89.94%  [===============================    ] 56.06 MiB/s, ETA 00:03

```

**Comment by animetosho** [comment]
I don't see the problem here? If you tell Nyuu to use a lot of connections, and constantly retry them, it will try to use a lot of connections and won't give up on failures.  
What do you think should be done?

**Comment by scriptzteam** [comment]
Probably on failure disconnect that connection and try again ? Or it already works that?

I have 50 connection and set as -n 30 so ?

**Comment by animetosho** [comment]
> Or it already works that?

It says so in the error message: `reconnecting after 5 second(s)...`

> I have 50 connection and set as -n 30 so ?

Servers not properly accounting for connection usage occur. You'll just have to deal with it...

**Comment by scriptzteam** [comment]
Probably it has something to do with this also - https://www.reddit.com/r/usenet/comments/5r8hct/usenetfarm_not_downloading/ he is downloading but still its weird ssl bug on usenet service providers ...

**Comment by animetosho** [comment]
That actually sounds different, but thanks for the info.

**Comment by scriptzteam** [comment]
it seems it was usenet.farm fail, from reddit -- 

[–]anc0dia 3

I had this problem too. This is what tech support told me :

SSL Port 563 is set to be more secure and the support for SSL3 is removed. You can only connect now with TLS1.0/1.1/1.2 to port 563. Please change this in your client settings or update to a newer version of your client.

If you can't upgrade or if there is no support for secure SSL in your client you can use port 443 instead of port 563.

[–]TheLynxy

I was having this problem as well. Connecting on port 563 and getting error:

    SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

I had the cipher manually specified as "RC4-MD5", removing that lets me connect with SSL again.

**Comment by animetosho** [comment]
> I had the cipher manually specified as "RC4-MD5", removing that lets me connect with SSL again.

Well, if you're specifically forcing an insecure cipher, I'm not surprised that things don't work.

Has absolutely nothing to do with SSL3, though I suppose if you've been using insecure settings and they decided to improve security, things will break on your end. Just leave things on their defaults for minimal fuss.
