### ISSUE TITLE
Limit Folder Size?

### ISSUE THREAD

**Issue by scriptzteam** [animetosho/Nyuu#19]
Would be really cool if we can have something like in config file what will skip with size over as defined in config.

Also second thing would be really cool to regex skip folders? Like: 
`/(Skip|Me|Too)/i`

Thx!

**Comment by animetosho** [comment]
How about `find . -type f -size 1G -not -iregex './(Skip|Me|Too)/.*' -print0 | xargs -0 nyuu [options]` ?
