### ISSUE TITLE
Average upload speed issue

### ISSUE THREAD

**Issue by usenethound** [animetosho/Nyuu#2]
I have noticed this for awhile and although it's not a huge deal I see that the upload speed reported seems to be based on the total time it takes to upload AND check the post rather than just the time it takes to upload it. This gives an inaccurate upload speed as the check can easily add 30+ seconds to the TOTAL file process time depending and how one sets their re-check delay and also how big the file may be. As an example, say I have a 300MB file and a 10 second delay... The file takes 10 seconds to upload then the check kicks in and adds another 10 seconds to the processing time. That in turn would take the speed reported and cut it in half. I like to have an accurate speed as sometimes it points to issues with a server and at that point I can switch to a server I may get better speeds on. Would it be possible to instead of...

posting time+check time=average upload speed
do
posting time=average upload speed

Thanks!

**Comment by animetosho** [comment]
Upload speed can be affected by lots of things, so I felt that the most accurate measure was to consider the total time.

Post checking runs in parallel with uploading, so there's no clear cut definition as to what the posting time was. One could just look at when new posts have all been submitted, but it's possible that uploading gets delayed by pending checks, so not entirely accurate either.

Nyuu focuses on overall speed, but it seems like you're more interested in network (upload) speed. I suppose network speed can be tracked and reported (cases such as unresponsive servers makes things ambiguous though) which may be closer to what you want. The numbers it reports may be unusually high though.
