### ISSUE TITLE
Segment bytes size is not consistent

### ISSUE THREAD

**Issue by kouze** [animetosho/Nyuu#20]
Hello,

I just have a question: the segment sizes are not consistent when posting with Nyuu. I've kept the default article-size to default value (700k), and the tool provides me segment size between 739000 and 740xxx bytes.

From my own understanding, this is not helping to have a perfect par2 repair management, as the par2 block size will be set on a fixed value, and this value should match the segment size used for posting, right?

Please let me know if my understanding is not correct, or else if you can set the segment size to a fixed value.

Thanks
kouze

**Comment by animetosho** [comment]
By 'segment size' are you referring to the article size?  
If so, how are you measuring this, that is, how are you determining that it is between 739000 and 740xxx?

Thanks

**Comment by animetosho** [comment]
Oh, would you perhaps be referring to the `bytes` attribute of segments in the outputted NZB?  
If so, that indicates post-yEnc sizes, so not a good indication of the actual data size. yEnc is a variable length encoding scheme and typically adds around 5% overhead, so the sizes you get sound like they're in that ballpark.

**Comment by kouze** [comment]
Hi,
sorry I was busy.
So yes, I was referring to the bytes attribute of segments in the outputted NZB.
I missed the yEnc encoding, which makes sense. So you are good, some other tools are not ;)

I'm closing the issue now.

Thanks,
kouze
