### ISSUE TITLE
When trying to upload a stream nyuu starts uploading but I get no status reports?

### ISSUE THREAD

**Issue by SanderM2** [animetosho/Nyuu#21]
I just tried uploading a stream by specifying 'procjson://"test.bin",1234313,"cat testfile"' and it started uploading (I can tell by looking at the network traffic) but the console stays empty. Nyuu doesn't report anything on the command line anymore.

I also tried with --progress http:0.0.0.0:1234 but that also doesn't work. It didn't even listen on port 1234.

Uploading the file by specifying "testfile" instead of the stream works perfectly fine.

Is this a bug or am I doing something wrong?

I know I just piped the file through cat but it's a test. I'm willing to use the streaming feature for something else. I've just provided an example that's easy to reproduce.

Thanks

**Comment by animetosho** [comment]
Thank you for the bug report!

Hopefully the above commit fixes it for you. Can you please confirm?

**Comment by SanderM2** [comment]
The console output is working now but an upload of a 6Gb stream failed:
/opt/nyuu/Nyuu/lib/article.js:75
                        throw new Error('Exceeded total file size');
                        ^
Error: Exceeded total file size
    at Object.generate (/opt/nyuu/Nyuu/lib/article.js:75:10)
    at /opt/nyuu/Nyuu/lib/uploadmgr.js:143:20
    at Object._readout (/opt/nyuu/Nyuu/lib/streamreader.js:123:5)
    at Object.onData (/opt/nyuu/Nyuu/lib/streamreader.js:41:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:547:20)

But I don't think uploading a 6Gb failed before so I think it's stream related?

**Comment by SanderM2** [comment]
I just notice it's showing the wrong size in this console message:
[INFO] Uploading 2645 article(s) from 1 file(s) totalling 1808 MiB

My upload stream was defined like this : 'procjson://"test.nzb",10485760032,"cat bintest"'
and "bintest" is exactly 10485760032 bytes in size.

I'm not sure where it gets 1808MiB from?

**Comment by SanderM2** [comment]
I replaced "size: m[1]|0," with "size: m[1]," and now it's reporting the size correctly.
Not sure if this can be considered a fix, as I don't know why "size: m[1]|0," was there in the first place...

**Comment by animetosho** [comment]
Gah, thanks for finding that!

> Not sure if this can be considered a fix

Should work fine :)
