### ISSUE TITLE
default From Header's dotless email addresses can be problematic

### ISSUE THREAD

**Issue by bgeet** [animetosho/Nyuu#26]
Some providers (f.ex. eweka) don't accept dotless email addresses and you get:
>[ERR ] NNTPError: Server could not accept post, returned: 441 Posting Failed. "From" Header not in Internet Syntax. E1

besides the default, also problematic in config-sample.json
>"from":               "Snazzy Poster <me@localhost>",

should be changed to 
>"from":               "Snazzy Poster <me@local.host>",

**Comment by animetosho** [comment]
That's a bit unfortunate :/  
Thanks for the suggestion!
