### ISSUE TITLE
don't ignore comments when `--subject` is specified

### ISSUE THREAD

**Issue by bgeet** [animetosho/Nyuu#27]
still want to be able to easily add comments when using a different subject formatting.
i'm changing comments all the time but subject formatting is a one-time change.
so please don't ignore comments (--comment/--comment2) when `--subject` is specified

**Comment by animetosho** [comment]
The `--subject` overrides the Subject header, so shortcuts like `--comment` kinda become ineffective.

You do raise an interesting use case scenario though - I've decided to support this by allowing `{comment}`/`{comment2}` placeholders in the `--subject` specification. Hope that gives you what you need.

**Comment by bgeet** [comment]
Much obliged.

One nitpick:
default value of `{comment}` is _undefined_ and not an empty string. so you always have to explicitly set `{comment}` when used in `--subject`.

**Comment by animetosho** [comment]
Oops, thanks for picking that up!
