### ISSUE TITLE
Clarify subdir config setting

### ISSUE THREAD

**Issue by RollingStar** [animetosho/Nyuu#3]
https://github.com/animetosho/Nyuu/blob/b37750ee8609e52595a6b70f97d8ba129c9bcb80/lib/fileuploader.js#L52

What happens when you give Nyuu a directory with `skip` enabled? In my testing, it told me "no files to process". I have a folder like this:

    c:\upload\test.txt
    c:\upload\test2.txt

When I do ` C:\files\nyuu.v0.2.4.win64\nyuu.cmd c:\upload\ -C custom-config.js` in Powershell, it gives me "no files to process" unless I enable `keep`. This is reasonable behavior, but it's not explained as well as it could be in the config file. I take "subdirectory" to mean folders within the folder given to Nyuu.

**Comment by animetosho** [comment]
Good point - thanks for the suggestion!
