### ISSUE TITLE
One file, each segment in different group?

### ISSUE THREAD

**Issue by scriptzteam** [animetosho/Nyuu#31]
Lest say i uploading blab.mp3 and i want each file segment in different group is that possible somehow ??

**Comment by animetosho** [comment]
Sounds like #16, the only difference being each segment to a different group? You'll need to set a function to the `Newsgroups` value in config.js to randomly select a group.

**Comment by scriptzteam** [comment]
Yeah but whcih function choosing file segment group? its always one file having its segments in only one group, and i mean having one file end in multiple groups per one segment

**Comment by animetosho** [comment]
Something like

~~~
Newsgroups: function() {
	var groups = ['alt.binaries.group1', 'alt.binaries.group2'];
	return groups[(Math.random()*groups.length) |0];
}
~~~

**Comment by scriptzteam** [comment]
Yeah thats great but for one single file? single file will end only in one group no? i mean if its possible to post segments of one single file to various diferrent groups :) if no then no xD

**Comment by animetosho** [comment]
Have you tried it?

**Comment by scriptzteam** [comment]
Yes thanks i know that looong time ago that this works :)

But i mean look this, if possible to post the segmets of file into various group not all segments of one file into one group :)
```
        <file poster="blublu" date="1509555814" subject="blahblah">
                <groups>
                        <group>alt.binaries.test</group>
                </groups>
                <segments>
                        <segment bytes="738107" number="1">EcXnOzUcOgNvMrAhRaAZfHt-1509555814123@test</segment>
                        <segment bytes="738086" number="2">fJqIdDiSsVjYoTtJqVyZxQu-1509555814127@test</segment>
                        <segment bytes="738188" number="3">GnAoRmWfViUoKaPgdYnAeJl-1509555815421@test</segment>
                        <segment bytes="738716" number="4">SmEpRmRTaDjYxmVlrMfTaHr-1509555815425@test</segment>
                        <segment bytes="738129" number="5">QxAqLrNcYgRdBmOySjRijGy-1509555816310@test</segment>
                        <segment bytes="738180" number="6">GsJlAuErYpRZaRzQmJzFoZd-1509555816314@test</segment>
                        <segment bytes="738153" number="7">FbThPoXfVfDiJfFqDIxTkNm-1509555816416@test</segment>
                        <segment bytes="738121" number="8">PjIjTgNrQeSPLaNbOsHnmGd-1509555816420@test</segment>
                        <segment bytes="738262" number="9">ZlGyQeWvLaXwOyWcoYkWfFi-1509555816555@test</segment>
                        <segment bytes="738024" number="10">UaZeLjQiGlDMtOoXwaQtTx-1509555816558@test</segment>
                        <segment bytes="738136" number="11">OvVaOoHfDlIvZtDpZoYlXw-1509555816656@test</segment>
                        <segment bytes="247042" number="12">CgQnFjVeVrfPwMayXdOjPt-1509555816659@test</segment>
                </segments>
        </file>
```

**Comment by animetosho** [comment]
Oh I see where you're coming from now.  
The segments should be posted to different groups, but the generated NZB will only use information from the first segment of the file, as that's what's needed to make it work.

Are you sure your 2nd NZB there is valid, and/or supported by any clients? What you're asking to do is rather odd, and I'm not really expecting it to be widely supported, if at all, anywhere.
