### ISSUE TITLE
How do I get this to work?

### ISSUE THREAD

**Issue by shillshocked** [animetosho/Nyuu#32]
nyuu -C /home/jblow/bin/Nyuu-master/config.json -t 'Test' -r keep -O blather.nzb
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 51.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/nyuu/node_modules/yencode/index.js:3:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

**Comment by animetosho** [comment]
How'd you install/build it? The error suggests that the yencode module was built for a different version of Nodejs than the one you're running with. Do you happen to have two versions of Nodejs and/or perhaps node-gyp is building for a different version?

**Comment by shillshocked** [comment]
So far I've tried downloading and running it, and the last time I tried using npm. I even tried using a different npm version. Same error all three times.

**Comment by animetosho** [comment]
Okay, a few things:

* What OS are you running?
* What version of Nodejs are you running, and how did you install it (package manager, build from source etc)?
* How did you install NPM?
* What is `nyuu` aliased to?
* Can you try running `npm install -g yencode` and then try again?
** If that fails, try `cd /usr/lib/node_modules/nyuu/node_modules/yencode && node-gyp rebuild` and post the output

Thanks

**Comment by shillshocked** [comment]
Currently, Arch with Linux 4.14.4-1-ck-sandybridge kernel.
Nodejs v9.2.0 - I don't remember how it was installed. (Same with NPM)
nyuu: /usr/bin/nyuu /usr/local/bin/nyuu

I tried that install code and got a warning:
"gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.7.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/yencode/.node-gyp"
It still completed, though.

That seems to have fixed it...but now I'm getting another unrelated error.

**Comment by animetosho** [comment]
Interesting. Seems to suggest that it's trying to build for node v4.7.2 for some reason? Anyway, glad that fixes it.

**Comment by shillshocked** [comment]
Yup, I now use the git version though for added features.
