### ISSUE TITLE
Altering Message-IDs

### ISSUE THREAD

**Issue by shillshocked** [animetosho/Nyuu#35]
Any way to remove nyuu from the Message-IDs without removing the randomization?

**Comment by animetosho** [comment]
Try adding `--message-id {rand:24}-{timestamp}` to the command.

**Comment by shillshocked** [comment]
Nice...

**Comment by shillshocked** [comment]
Got this on a post:
[WARN] Got "441 435 Bad Message-ID" response when posting article LXDqWvBe1KLmlMOGLF9MSnEU-1513557837476; will retry (attempt 1/1)
[ERR ] NNTPError: Server could not accept post, returned: 441 435 Bad Message-ID (use `skip-errors` to ignore)

It didn't do it before. Not sure what changed.

**Comment by animetosho** [comment]
As the error says, the server doesn't like the message ID.
