### ISSUE TITLE
heavy cpu usage / poor performance with 0.3.6

### ISSUE THREAD

**Issue by kuku5hka** [animetosho/Nyuu#42]
ouch, tried to switch to 0.3.6, cpu core usage went directly to the roof, post queue went empty and consequently effective speed dropped..

0.3.6

![nyuu036](https://user-images.githubusercontent.com/5408120/35193275-47b6aaa4-feb1-11e7-9703-a3b95defdc34.png)

0.3.4

![nyuu034](https://user-images.githubusercontent.com/5408120/35193276-47dd04b0-feb1-11e7-8543-e96ec4132103.png)

**Comment by animetosho** [comment]
Looks like you may have hit a live-lock condition (I assume it gets stuck). I'm unable to reproduce it however - are you able to post your command/config?

**Comment by kuku5hka** [comment]
oh. managed to localize it. turns out that using placeholders in subject causes it.
my minimized json

{
	"host":               "xxx",
	"port":               563,
	"ssl":                true,
	"ignore-cert":        false,
	"user":               "xxx",
	"password":           "xxx",
	"connections":        30,
	"article-size":       "700K",
	"from":               "x<x@x.x>",
	"groups":             "alt.binaries.x",
	"check-connections":  0,
	"out":                null,
	"quiet":              false
}


and it's runned smth like this
for /d %c in (*.*) do x:\nyuu\nyuu.exe --config x:\nyuu\nyuu.json -o "%c".nzb "%c" --subject "[{filenum}/{files}] %c"

when i remove [{filenum}/{files}] everything goes smootly just like in old version
when there's just filenum - i see a decent cpu load increased, with two of them - it takes a full core load of my not so new conroe.

**Comment by animetosho** [comment]
Thanks for finding that!
