### ISSUE TITLE
[ERR ] Unexpected fatal exception encountered, stack trace below

### ISSUE THREAD

**Issue by scriptzteam** [animetosho/Nyuu#44]
What can cause this? Some uploads great then it fail then again works ...

My not recommended fix: commented it so now its `//throw err; ` 
and it works :D 
```
[ERR ] Unexpected fatal exception encountered, stack trace below
/root/Nyuu/bin/nyuu.js:1134
                        throw err; // this seems to change the exit code a bit :/
                        ^

Error: Callback was already called.
    at /root/Nyuu/node_modules/async/dist/async.js:955:32
    at /root/Nyuu/lib/nntp.js:467:4
    at Array.forEach (native)
    at Object.NNTP._callMulti (/root/Nyuu/lib/nntp.js:466:7)
    at /root/Nyuu/lib/nntp.js:490:10
    at Socket.<anonymous> (/root/Nyuu/lib/nntp.js:560:4)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
```

**Comment by animetosho** [comment]
These sorts of bugs are tricky to figure out. Does it happen often? Are you able to provide more information, such as the full log, command options, and how far the process went before this occurred?

I've made some changes to hopefully make it easier to track it down a bit, but ultimately I don't know the cause of it.
