### ISSUE TITLE
Nyuu + ParPar and Obfuscation

### ISSUE THREAD

**Issue by apax0r** [animetosho/Nyuu#48]
Hi, i just got Nyuu up and running, working great! But the documentation is limited (or i cant read very well).

But how do i get parpar to work with Nyuu? trough a bash script? And how do i config Nyuu to do Obfuscation? I was reading something in https://github.com/animetosho/Nyuu/issues/10 but i dont know how to set it up in my config.js

Any help would be great!

Edit:

I tryed to put in the example code you posted in https://github.com/animetosho/Nyuu/issues/10 into my config, this is the output:

> [2018-07-30 11:43:11.412][ERR ] Unexpected fatal exception encountered, stack trace below
>  
> /home/user/Nyuu/bin/nyuu.js:1056
>                 throw err; // this seems to change the exit code a bit :/
>                 ^
> TypeError: filename.replace is not a function
>     at module.exports.nzb.overrides.subject (/home/user/Nyuu/config.js:118:20)
>     at /home/ap0x/Nyuu/lib/uploadmgr.js:206:14
>     at Array.forEach (native)
>     at Array.<anonymous> (/home/user/Nyuu/lib/uploadmgr.js:202:18)
>     at Object.<anonymous> (/home/user/Nyuu/lib/filereader.js:163:10)
>     at Array.forEach (native)
>     at Object.BufferedFileReader.onEnd (/home/user/Nyuu/lib/filereader.js:162:5)
>     at /home/user/Nyuu/lib/filereader.js:110:11
>     at FSReqWrap.wrapper [as oncomplete] (fs.js:576:1
> 

My OS is Ubuntu 16.04 LTS Server

**Comment by animetosho** [comment]
> how do i get parpar to work with Nyuu?

As of now, they are two completely separate applications - there is no special integration between the two. As such, it would be like every other uploader out there - you create the PAR2 before the upload (and you can 'automate' this via a bash script).

> And how do i config Nyuu to do Obfuscation?

This highly depends on how you want to do it. Nyuu doesn't provide any specific built-in way to do it, mostly because everyone has their own idea of how it should be done. See the [full help file](https://raw.githubusercontent.com/animetosho/Nyuu/master/help-full.txt) for a list of all available options, and pick what you want to change. Also see #43

**Comment by apax0r** [comment]
Okey, thanks for the info, gonna look up on how to write the bash script for the parpar part, or maybe you can point me an existing one?

Regarding obfuscation, this looks harder to get it to work. As you see i tryed what you posted in https://github.com/animetosho/Nyuu/issues/10 but i got an "Unexpected fatal exception encountered".

This is why i opened an ticket here, as i understand there is no "default" way to do this. Uhm, i guess i have to try my own way to do this..

**Comment by animetosho** [comment]
Bash script would probably look something like:

```
#!/bin/sh
parpar [desired options] -o ${PWD##*/} -- $@
nyuu [desired options] -- $@
```

Save it in your PATH somewhere so you can call it anywhere (or use an alias).  
(haven't tested it, but might point you in the general direction)

> Regarding obfuscation, this looks harder to get it to work

If you don't really know Javascript, I'd recommend against trying to edit config.js - use the command line options instead. If you need advanced functionality, then you'll have to revert to code.  
What exactly are you trying to achieve?

**Comment by apax0r** [comment]
Okey thanks.

What im trying to do is that i want to hide the release name: My.Fine.Upload.x264.1080p-MyGRP to 124asd123.nzb but the index site gets the right upload name.

Thanks for helping out :)

**Comment by animetosho** [comment]
No worries. Feel free to open this again if you have any further issues.

**Comment by ndessenius** [comment]
> Indexers usually don't process and/or use the uploaded filename as the release name.
> You'd provide it separately via a form-field or API.
> I made a PowerShell-Module to control everything:
> 
> * RAR'ing (different filesizes for each file or Auto-Mode based on File/Folder-Size)
> * PAR'ing (using ext. par2j64 10%)
> * Obfuscation (either based on MacDbl/MD5's or Scramble-Modes (2) (randomizing filenames))
> * construct proper command for NYUU

Would you share this PS-Module? I'm pretty interested.
