### ISSUE TITLE
-k 0 parameter does not deactivate post checking?

### ISSUE THREAD

**Issue by Tensai75** [animetosho/Nyuu#49]
Hi Anime Tosho

I have some issues regarding the post check.

According to your help information, post check by default is disabled (-k 0). However, when starting an upload without setting the option -k, in the overview message at the end it is nevertheless stated "Articles checked: XXX (100.00%)". Even if you explicitly set the option -k 0 the articles still get checked (at least according to the overview at the end). How do I ensure that post check is disabled?

Also the connections settings are not clear to me when I want to use post check. If I want to use the same server for upload and post check and the server allows for max  X connections, how do I have to set the -n and the -k option correctly to use all the X connections without running into "too many connections" errors? So if I set
-n X -k Y
will then X+Y connections be used and I better should set:
-n X-Y -k Y 
or is -n X the max connections used by nyuu, and nyuu will take care by itself to only use X-Y connections for upload and y connections for post check?

Thanks for this great program and best regards!

Tensai

**Comment by animetosho** [comment]
Thanks for bringing up these issues. I've made clarifications which hopefully address these.

Post checking: setting check connections to 0 does disable it. Internally, Nyuu handles this by skipping the check operation and instantly marking posted articles as checked (this simplifies overall design). If you've enabled more extensive logging, it just dumps out this internal info. I've made a change to hide this text if post checking is disabled, to avoid confusion.

Connection usage with checking: your first understanding is correct, `--check-connections` creates _additional_ connections to those specified by the `--connections` option. I've tweaked the help text to hopefully clarify this a bit.  
As a bit of an aside, it may not be a good idea to push the connection limit that your host provides. Sometimes I find that their accounting of connections isn't always what you think it'd be. Nyuu also does re-create connections when it encounters an error, which may perturb the limit somewhat. Furthermore, Nyuu's default action on connection failures (after a certain number of retires) is to halt the uploading process (I'm not sure if this is a good default option, but you can change this via `--skip-errors connect-fail` option).

In future, I may remove the `--check-connections` option as I don't particularly like the idea of dedicating a connection just for checking (Nyuu should be able to automatically balance posting/checking across all available connections). If and when that happens, it should remove any confusion around this altogether.

Thanks again!

**Comment by Tensai75** [comment]
Hi Anime Tosho

Many thanks for your clarifications and further explanations.
Very helpful indeed.

And thanks once again for writing this wonderful piece of software!

Regards, Tensai
