### ISSUE TITLE
Feature Request: Maximum upload speed.

### ISSUE THREAD

**Issue by sirjaymz** [animetosho/Nyuu#51]
Feature Request:
To limit the maximum upload speed of Nyuu to a specified value. If it's not achieved, it does not throttle, however, if the max upload speed is achievable, allow user to specify maximum upload speed.

Suggestion:

--max-upload-speed                            Set's maximum upload speed of all connections combined to X speed per second specified in KiB, (kilo-bytes per second)
                                                              e.g.      3500 or 10000
                                                              e.g. (--max-upload-speed 3500)

**Comment by scriptzteam** [comment]
This can be done by other softwares that can limit bw :) but anyway great request ...

**Comment by animetosho** [comment]
Thanks for the suggestion!

**Comment by shillshocked** [comment]
Great idea. What alternative software would you recommend pre-implementation?
