### ISSUE TITLE
Code 499

### ISSUE THREAD

**Issue by petredr** [animetosho/Nyuu#52]
I use nyuu on Windows. I love it. Thanks so much for this awesome software.
I do have an issue (usually with really large uploads, often greater than 150GB)
This is the error I get:
[ERR ] Post rejected (Unexpected response to post-upload (code: 499): Remote server unavailable.) for article xxx@nyuu; continuing regardless
If i don't use the -e switch it basically stops once this error comes up.
Is it possible to basically:
1) retry posts after getting this error rather than stopping/skipping
2) create a temp nzb of posts that have been checked (perhaps in a temp nzb folder as well as memory). If any such error is encountered and the posting has to be restarted all posts are checked vs the temp nzb so that they are not repeated. Once the posting is completed without errors, the temp nzb is deleted.

Thanks

**Comment by animetosho** [comment]
Thanks for raising the issue!

For your first point, try supplying the `--retry-on-bad-resp` option on your command line. I'm considering making this option on by default.

For your second suggestion, unfortunately Nyuu currently has no support for resuming uploads. There's an ugly hack I use at the moment, which involves dumping out failed posts, then attempting to re-upload these at a later time (see `--dump-failed-posts` and `--input-raw-posts` options in the [full help file](https://github.com/animetosho/Nyuu/blob/f1caf0e91ec7de8205ab7ecea26612b1eeee49b2/help-full.txt#L321)).

**Comment by petredr** [comment]
Thanks so much, will try the first option.
I doubt I can use the dump because I use NZBs and I expect the dumped posts don't get written to NZBs but its good to know.
The only other suggestion I have is multiple server support (with the config.json file) where a backup server can be specified along with options for either random posting to each or backup mode (switch to backup server in case of errors).

**Comment by animetosho** [comment]
> I expect the dumped posts don't get written to NZBs

They actually do. If you ignore errors, Nyuu just treats failed posts as successful.

The current multi-server support is very basic and crude at the moment. Being able to specify some rules around server selection is certainly a good idea, so thanks for raising that!

**Comment by petredr** [comment]
Option 1 worked, just did a large post and it retried multiple 499 errors!
I suspect it has to do with I/O and system resources as well as this doesn't happen often and only happens on my slow system (non-SSD).
It would be nice to set it to default on the next release so those who haven't encountered this error won't have to as the cost of retrying posts on this error is far less than the potential reposting of an entire set due to a fatal error.
