### ISSUE TITLE
is it possible to fully automate it? 

### ISSUE THREAD

**Issue by JavascriptHiFi** [animetosho/Nyuu#53]
Hey I was wondering is it's possible to fully automate it to post mkv files or folders without the uploader interaction

Thank you

**Comment by animetosho** [comment]
I'm not sure what you mean. Nyuu is a command line tool - you can automate it in any way that you would with any other command line tool.

**Comment by animetosho** [comment]
Unless you have a very particular reason for such, unfortunately no.

**Comment by JavascriptHiFi** [comment]
can't speak about here
