### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by jhdscript** [animetosho/Nyuu#56]
First: big thanx for your code you save me a lot of time. I m very impress about your soft and the code !

Atm i no found any issue but i have a question: i m looking for the same app but to process download from an nzb.

Maybe have you something like this in your toolbox. A compatible windows / linux app will be appreciate, in nodejs maybe.

Thanx a lot

**Comment by animetosho** [comment]
https://www.reddit.com/r/usenet/comments/19ikje/cli_based_linux_nzb_download_utility/  

Search for more.

**Comment by jhdscript** [comment]
do you develop parity file generation in future release ?

**Comment by animetosho** [comment]
See https://github.com/animetosho/Nyuu#planned-features
