### ISSUE TITLE
Feature Request: Adding password to NZB

### ISSUE THREAD

**Issue by OfficerDoofy** [animetosho/Nyuu#59]
Hiya, special officer Doofy reporting! xD

I was wondering is there any possibility to add option to add password to created NZB after NZB was created? Something like this :

<head> 
<meta type="password">PasswordGoesHere</meta> 
</head>

PS Thank you for this dope script!

**Comment by animetosho** [comment]
Hi,  
Try the option `-M password=PasswordGoesHere`
