### ISSUE TITLE
Obfuscated subject and overwrite subject error

### ISSUE THREAD

**Issue by scriptzteam** [animetosho/Nyuu#60]
Hi i am getting this error -> "TypeError: filename.replace is not a function"

nyuu config

```
       overrides: {
                // here you can override values for NZB <file> entries
                // if unset, will use the NNTP header values from the first segment of the file
                // can be set to a function, which will be called with args(header_value, filenum, filenumtotal, filename, size, parts)
                subject: function(header_value, filenum, filenumtotal, filename, size, parts) {
    return '[' + filenum + '/' + filenumtotal + '] - "' +
        filename.replace(/"/g, '') +
        '" yEnc (1/' + parts + ') ' + size;
},
```

**Comment by animetosho** [comment]
Are you using an old version of Nyuu, or have a config file from an old version?  
The argument ordering was changed in v0.3.7 to `(filenum, filenumtotal, filename, size, part, parts, header_value)`, so perhaps give that a try.

**Comment by ANTiGEN0M** [comment]
> Hi i am getting this error -> "TypeError: filename.replace is not a function"
> 
> nyuu config
> 
> ```
>        overrides: {
>                 // here you can override values for NZB <file> entries
>                 // if unset, will use the NNTP header values from the first segment of the file
>                 // can be set to a function, which will be called with args(header_value, filenum, filenumtotal, filename, size, parts)
>                 subject: function(header_value, filenum, filenumtotal, filename, size, parts) {
>     return '[' + filenum + '/' + filenumtotal + '] - "' +
>         filename.replace(/"/g, '') +
>         '" yEnc (1/' + parts + ') ' + size;
> },
> ```

for what? you scrap indexers like a monkey why would you need to use this LEGENDARY T00L
