### ISSUE TITLE
Mac binaries

### ISSUE THREAD

**Issue by tjesp** [animetosho/Nyuu#62]
I am having huge problems building this on Mac OS. I am not a programmer and I have no idea what node is complaining about.

Is it possible we can have a Mac binary build? I know its a bit much to ask if you need to get a Mac but is there a possibility that someone could make that build for you?

**Comment by tjesp** [comment]
Or perhaps you can help with my issue. This is what I get. I have no idea what to do:

Thomass-Mac-mini:Feed thomasjespersen$ npm install -g nyuu
/Users/thomasjespersen/.npm-packages/bin/nyuu -> /Users/thomasjespersen/.npm-packages/lib/node_modules/nyuu/bin/nyuu.js

> yencode@1.0.8 install /Users/thomasjespersen/.npm-packages/lib/node_modules/nyuu/node_modules/yencode
> node-gyp rebuild

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/thomasjespersen/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/Cellar/node/12.12.0/bin/node" "/Users/thomasjespersen/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/thomasjespersen/.npm-packages/lib/node_modules/nyuu/node_modules/yencode
gyp ERR! node -v v12.12.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yencode@1.0.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yencode@1.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thomasjespersen/.npm/_logs/2019-10-22T20_23_48_295Z-debug.log

**Comment by animetosho** [comment]
Unfortunately I don't have a Mac, so what I can do on the platform is very limited.

As for your build error, it looks like you need [Xcode](https://developer.apple.com/xcode/) installed. From searching around, you can probably get it from the App Store.

**Comment by tjesp** [comment]
Thanks.

I am a bit further now. Now I get this. There were more errors than this. Tell if you need them all:

../yencode.cc:1544:6: error: variable has incomplete type 'void'
void init(Handle<Object> target) {
     ^
../yencode.cc:1544:11: error: use of undeclared identifier 'Handle'
void init(Handle<Object> target) {
          ^
../yencode.cc:1544:18: error: 'Object' does not refer to a value
void init(Handle<Object> target) {
                 ^
/Users/thomasjespersen/Library/Caches/node-gyp/12.12.0/include/node/v8.h:3400:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../yencode.cc:1544:26: error: use of undeclared identifier 'target'
void init(Handle<Object> target) {
                         ^
../yencode.cc:1544:33: error: expected ';' after top level declarator
void init(Handle<Object> target) {
                                ^
                                ;
7 warnings and 11 errors generated.
make: *** [Release/obj.target/yencode/yencode.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/Cellar/node/12.12.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/thomasjespersen/Downloads/Feed/Nyuu/node_modules/yencode
gyp ERR! node -v v12.12.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN rollback Rolling back yencode@1.0.8 failed (this is probably harmless): /Users/thomasjespersen/Downloads/Feed/nyuu/node_modules/yencode is not a child of /usr/local/lib
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yencode@1.0.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yencode@1.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thomasjespersen/.npm/_logs/2019-10-22T21_04_37_010Z-debug.log

**Comment by animetosho** [comment]
It looks like you're using Node v12.x, where [it currently doesn't work](https://github.com/animetosho/node-yencode/issues/5). Are you able to uninstall Node v12 and try v10 instead?

**Comment by tjesp** [comment]
Yes I could! Thanks. Now it is working.

PS:
Any other Mac users should use "brew install node@10"

**Comment by animetosho** [comment]
Thanks for trying it out and posting the results!
