### ISSUE TITLE
I just used nyuu to upload to usenet but the nzb shows like this 

### ISSUE THREAD

**Issue by JavascriptHiFi** [animetosho/Nyuu#64]
https://i.imgur.com/4gROa2v.jpg

any idea why?

**Comment by Squiggles4321** [comment]
Hi,
What is the issue?  It appears to have posted what you asked it to.
-Squigs

**Comment by JavascriptHiFi** [comment]
it should be in par files no?

**Comment by Squiggles4321** [comment]
Hi,
NYUU is just the poster.  Anything related to the RAR and PAR creation is done by external programs (rar and ParPar or par2create).  Once you have your RARs and PARs in a directory NYUU can post them.
-Squigs

**Comment by JavascriptHiFi** [comment]
Hi
so something like this 

Folder>>sent to par watch>>parpar gets it>>output>>Nyuu ups?

**Comment by Squiggles4321** [comment]
Source file -> obfuscation -> rar archive -> par creation on rar output -> nyuu.

This project is a bash script that automates a lot of the steps.  You could adapt to your specific needs if it doesn't cover what you need.

https://github.com/0xelion/nzb-safeloader

**Comment by JavascriptHiFi** [comment]
in the config file
# Output directory
CPL="$DIR/Completed"
is for   .nzb correct?

**Comment by JavascriptHiFi** [comment]
Hi
Thank you for your help you guys are awesome! much appreciated it
