### ISSUE TITLE
Unexpected fatal exception encountered

### ISSUE THREAD

**Issue by BlepingMatrix** [animetosho/Nyuu#69]
[ERR ] Unexpected fatal exception encountered, stack trace below
/home/USER/Nyuu/bin/nyuu.js:1086
                throw err; // this seems to change the exit code a bit :/
                ^

ReferenceError: self is not defined
    at NNTP._onData (/home/USER/Nyuu/lib/nntp.js:428:42)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

For some reason I've recently started encountering this error. It happens randomly there's no precise reason to it I don't think. That said it could be due to multiple instances of Nyuu running but I can't be sure. Was wondering if you knew why it was happening? (I am using the git version of nyuu)

**Comment by animetosho** [comment]
Thanks for reporting that!

It looks like a bug which is triggered when the server rejects the post (441 response). I haven't tested the fix yet, but I imagine it should work.

**Comment by BlepingMatrix** [comment]
@animetosho Hey there. I applied the fix (git pull) and now the error's changed a bit. Not sure if its the same reason or another reason. Here is the log:
[ERR ] Unexpected fatal exception encountered, stack trace below
/home/USER/Nyuu/bin/nyuu.js:1086
                throw err; // this seems to change the exit code a bit :/
                ^

Error: Callback was already called.
    at /home/USER/Nyuu/node_modules/async/dist/async.js:966:32
    at /home/USER/Nyuu/lib/nntp.js:494:4
    at Array.forEach (<anonymous>)
    at NNTP._callMulti (/home/USER/Nyuu/lib/nntp.js:493:7)
    at /home/USER/Nyuu/lib/nntp.js:517:10
    at TLSSocket.<anonymous> (/home/USER/Nyuu/lib/nntp.js:591:4)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:203:15)
    at _handle.close (net.js:606:12)
    at TCP.done (_tls_wrap.js:388:7)

**Comment by animetosho** [comment]
That looks like a different issue :/

Could you post the log of what happened before the error?

**Comment by BlepingMatrix** [comment]
Starting Usenet Upload...
[INFO] Uploading 62 article(s) from 4 file(s) totalling 39.96 MiB
[INFO] Reading file 421c1add3944ca.par2...
[INFO] Reading file 51c4085f069fe5.par2...
[INFO] Reading file cb54ebabc49d9...
[INFO] Reading file 33184ac5a4099...
[INFO] All file(s) read...
[ERR ] Unexpected fatal exception encountered, stack trace below
/home/USER/Nyuu/bin/nyuu.js:1086
                throw err; // this seems to change the exit code a bit :/
                ^

Error: Callback was already called.
    at /home/USER/Nyuu/node_modules/async/dist/async.js:966:32
    at /home/USER/Nyuu/lib/nntp.js:494:4
    at Array.forEach (<anonymous>)
    at NNTP._callMulti (/home/USER/Nyuu/lib/nntp.js:493:7)
    at /home/USER/Nyuu/lib/nntp.js:517:10
    at TLSSocket.<anonymous> (/home/USER/Nyuu/lib/nntp.js:591:4)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:203:15)
    at _handle.close (net.js:606:12)
    at TCP.done (_tls_wrap.js:388:7)

Here you go!
Happened right after "All Files Read" (I've changed the posting file names for obvious reasons)

**Comment by animetosho** [comment]
Thanks for the info!

Would you be able to test the latest code to see if it fixes that? If it doesn't, would you be able to command/settings you've used?

**Comment by BlepingMatrix** [comment]
@animetosho I just applied the fix. Tested it on around 15 files nothing yet. Let's see if the error occurs again. It's being tested on around a thousand or so more files so ...it might occur again. (That said UsenetFarm was moving their hardware to a new location and they did apply a fix to cull the auth issues last night. So can't be sure if I can replicate the error again)
command: nyuu -C ~/.config/config.json -o "${NAME}.nzb" "${TO_UPLOAD}"
other than this the config.json matches the default config

**Comment by animetosho** [comment]
Awesome, thanks for confirming!

**Comment by ANTiGEN0M** [comment]
too much small files ;O

**Comment by BlepingMatrix** [comment]
> Awesome, thanks for confirming!

@animetosho I've been posting almost constantly since, no errors yet. So it's pretty stable now.

**Comment by animetosho** [comment]
Awesome, thanks for reporting back!
