### ISSUE TITLE
Feature request: Move check-connections to a server option

### ISSUE THREAD

**Issue by AssRap3r** [animetosho/Nyuu#71]
I'm curious as to how post-checking is supposed to work with a multi-server setup since there doesn't appear to be any way to define a maximum number of allowed connections for a server which becomes a problem when you've got a high number of posting/checking connections

for example:
Server 1: NewsDemon with 10 posting connections (out of 20 allowed total)
Server 2: ViperNews with 10 posting connections (out of 20 allowed total)
Check-Connections: 20

with the current implementation Nyuu sees Server1 & Server 2 as both having 30 available connections. I think that checking options should be merged with server options so we can have more control over connection counts

**Comment by animetosho** [comment]
Nyuu has the notion of post connections and check connections for each server. If you're using a multi server setup, you can specify the number of check connections that exist for each server (`checkConnections` option in config.js), just like you do for post connections (`postConnections` option).

Multi-server isn't really supported in the command line or JSON config file. Essentially, options specified there will override the defaults from config.js for all servers. So if you're specifying the check connections option via CLI or config.json, it'll override the `checkConnections` option for both your servers and set it to that many connections, as you mention in your example.

Note that, like posting, checking is done randomly across servers, so it's possible posts get checked on the same or different server from which it was posted on.

**Comment by AssRap3r** [comment]
ooh, that makes more sense. I never touch the config.js and always use the json config instead. I'll update my configs later and give it a try. you can close this since it's already implemented :)

**Comment by animetosho** [comment]
> I never touch the config.js and always use the json config instead

How have you managed to get multiple servers working? I didn't think it was possible to do that via JSON config.

**Comment by AssRap3r** [comment]
I just replicated the " *** Server Options *** ":0, part in the json, now that I think of it I'm not even sure if it worked. the only reason i'm using multi-server is for a speed boost since ND's EU servers are slower than Viper's, unfortunately since there's not a backup server feature it means rolling the dice with vipers post acceptance :'(

**Comment by animetosho** [comment]
Ah yes, that doesn't work - presumably what comes at the end will override everything prior. Multi-server is only supported in config.js by giving an array of server connections.
