### ISSUE TITLE
[Feature Idea] Encryption on the fly

### ISSUE THREAD

**Issue by scriptzteam** [animetosho/Nyuu#72]
Hello,
the main idea is to fetch content of file(s) and while upload, encrypt it (will probably slow upload but thats not that bad) with password. The best idea is to store password in nzb file itself or in nzb filename or maybe just define --pass blahblah

I dont mean just to rar and add password but some on the fly encryption with pgp or so.
Original files stay on disk, nothing changed, no need to rar, unrar.

Decrypting will be another task, but on linux its pretty easy, for example with sabnzbd just set postprocess script to decrypt it with password...

**Comment by animetosho** [comment]
If you can obtain the final encrypted filesize and don't mind the convoluted syntax, the `procjson://` input feature allows you to stream output from a process as an input file.

For example, if your source file *secret_file.txt* will encrypt to 1000 bytes: `nyuu 'procjson://"encrypted_file.dat",1000,"cat secret_file.txt | encrypt"'

**Comment by scriptzteam** [comment]
thx so much :)
