### ISSUE TITLE
On post failure use other provider?

### ISSUE THREAD

**Issue by scriptzteam** [animetosho/Nyuu#74]
Lets say one provider keeps getting posting failures - 440 error, so while one usenet provider is getting error 440 lets use another provider from config, is it possible?

**Comment by animetosho** [comment]
Thanks for the suggestion - it's a nice idea.

Currently you can specify multiple hosts, but uploading is just randomly distributed amongst connections. If you set Nyuu to ignore post errors, it'll eventually complete over the connections that accept the posts, though it'll keep trying on all existing connections, and it's not a binary 'switch over' that you probably want.

Unfortunately, you'd probably want some saved state for this to work properly \*, as you probably don't want to be continually retrying to provider with failures. If uploads are being done via a script, perhaps it could periodically login and check the welcome message that the NNTP server returns (whether posting is allowed or not) and switch over if it detects a failure.

\* if so, this sort of saved state is probably beyond the scope of what I want to do with Nyuu
