### ISSUE TITLE
Problem with installing on openmediavault (debian)

### ISSUE THREAD

**Issue by borry1973** [animetosho/Nyuu#8]
Hi there,

I`ve tried to install Nyuu on my openmediavault (debian jessie) system.
When I try to run Nyuu with node nyuu test.tar.bz, I keep getting the next error message.

module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /media/820d250a-a6a5-4d8b-b9fe-1d1861798ac7/BigNAS/Nyuu/node_modules/yencode/build/Release/yencode.node: failed to map segment from shared object: Operation not permitted
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/media/820d250a-a6a5-4d8b-b9fe-1d1861798ac7/BigNAS/Nyuu/node_modules/yencode/index.js:3:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by animetosho** [comment]
This appears to be a system error as opposed to an issue with Nyuu, as your system is rejecting the `dlopen` call.

Looking at your path, I suspect that your NAS may be mounted as non-executable (`noexec` option). If this is the case, there's a few options:

1. Move the Nyuu folder to a location that allows dlopen (say, your home directory). This is the preferred solution
2. Install the *yencode* module to the global location, as this is the only custom module imported with dlopen. To do this, use the command `npm install -g yencode` and then remove the `Nyuu/node_modules/yencode` folder
3. Mount the drive as executable (may reduce security, not recommended)

If the above doesn't help, try searching the error: `failed to map segment from shared object: Operation not permitted`

**Comment by borry1973** [comment]
Hi there,
Thnx for your fast reply.
I moved the complete Nyuu installation map to /home, this solved the problem.
Upload speed is higher than my former upload program (newsmangler).

**Comment by animetosho** [comment]
Glad that worked!
