### ISSUE TITLE
Updated Pre-Built Binaries

### ISSUE THREAD

**Issue by cavalia88** [animetosho/Nyuu#82]
Would it be possible to update the Pre-Built Binaries for Nyuu? The most recent version is v0.3.8 which was released in May 2018.

I think there have been some updates to Nyuu since then. The old v0.3.8 pre-built binaries doesn't seem to have the " --nzb-password" function

**Comment by animetosho** [comment]
Yeah, I had planned to do a v0.3.9 release sometime, but I was trying to also build a newer version of Node, but will need to figure out how to get all the build scripts working.

Sorry for the delay - I should get to it eventually.

**Comment by animetosho** [comment]
Added a new release.

FYI @poldi1405 if you want to update the Arch package.
