### ISSUE TITLE
[workaround] unhandled rejections during build

### ISSUE THREAD

**Issue by nonspin** [animetosho/Nyuu#85]
I had to add `'--unhandled-rejections=strict'`
to: build.js  (Ln 51-52)

```
// invoke nexe
var configureArgs = [staticness, '--without-dtrace', '--without-etw', '--unhandled-rejections=strict', '--without-npm', '--with-intl=none', '--without-report', '--without-node-options', '--without-inspector', '--without-siphash', '--dest-cpu=' + buildArch];
```
build_success
node v12.20.0 / win x64

Thanks for the all the hard work you've put into it. 
Appreciated

**Comment by animetosho** [comment]
Thanks for the info, but I don't get it.

I can't find `--unhandled-rejections` as a configure flag. Only reference I can find is [a Node flag](https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode) - is that it? And even if so, from the documentation, it doesn't sound like it should make a difference.

What issues are you getting without the flag?

**Comment by nonspin** [comment]
w/out it, it won't build successfully ... i'll post some more details about the exception thrown

**Comment by nonspin** [comment]
Sorry, it took me a while to figure this one out.
I didn't realize, that - while building - my repo-drive ran full, causing one process  not to report back ..  triggering the exception and the workaround
Of course, adding it - with the temp/cache cleared the build would eventually finalize.

.. My bad. Sorry =/

**Comment by animetosho** [comment]
Ah I see, thanks for clearing that up!
