### ISSUE TITLE
Post retry handling question

### ISSUE THREAD

**Issue by jrehmer** [animetosho/Nyuu#97]
I am using nyuu with these flags:

> -k1 --check-tries 3 --check-delay 5 --check-post-tries 3 --dump-failed-posts

Occasionally due to things happening upstream an article is accepted by the server I am posting to, but not relayed to the server responsible for filtering and propagating articles.  nyuu reports this when it runs into this condition:

> [WARN] Post check failed to find posted article MESSSAGE-ID; re-posting... (retry 1/3)

It never says it had to retry again or failed, but when I go check for that message ID it is never found.  Is nyuu regenerating the message with a unique Message-ID? 

I run the server I am posting to, and what is happening there is nnrpd is accepting the article but the upstream nnrpdposthost is not, so the article is filed in the incoming folder until a cron kicks off to process those 'failed' posts to the upstream.

So even though nyuu says the post didn't fail and only one retry was attempted, the Message-ID reported never did get propagated unless I wait for that cron on the posting server to process those.  Now I'm wondering if nyuu is generating a new article with a unique Message-ID and I should not be re-processing the failed articles on the posting server.

**Comment by animetosho** [comment]
> Is nyuu regenerating the message with a unique Message-ID?

Yes. You can suppress this behaviour with the `--keep-message-id` flag.

It's done like this because of issues like you describe - if the post-to server has the article but the check server doesn't, it's possible that re-posting would cause the article to be rejected, however Nyuu has no real way of understanding why. Regenerating the Message-ID removes that failure possibility.

**Comment by jrehmer** [comment]
Thanis, and apparently I need to take more time and read all of the options described in --help-full because I see there is also the option to change Message-ID generation which my other post inquires about.  Thanks for your help and sorry for failing at life and reading your extensively documented list of options.
