### ISSUE TITLE
Feature request: bring back PowerPost style Message-ID generation as an option

### ISSUE THREAD

**Issue by jrehmer** [animetosho/Nyuu#98]
I know some people hate it, but the way PowerPost and similar tools generate the Message-IDs containing partXXXofXXX to represent the part numbers is very valuable to me.  It makes it ridiculously simple for me as a user, and a server admin, to see exactly which articles came through and which did not in various situations.

**Comment by animetosho** [comment]
I'm not entirely sure what you're looking for, but perhaps adding `part{0part}of{parts}` to the `--subject` parameter is what you want?

**Comment by jrehmer** [comment]
PowerPost Message-IDs look like this:
<part25of168.EU4wMMScxjDSDAXad8aS@powerpost2000AA.local>

The only part of the Message-ID that changes between articles is the part numbers.

Being a server admin, it's easier for me to look at logs, which only contain a Message-ID and no other information that I may need to pull out of overview data.

**Comment by animetosho** [comment]
Oops, I thought you meant subject. But the same applies for the `--message-id` option, so you probably want something like `--message-id "part{part}of{parts}.${rand(20)}@powerpost2000AA.local"`

**Comment by jrehmer** [comment]
Yep, as in #97, I did not fully read this feature was already there, thanks again.
